import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface GameLobbyProps {
  onJoinGame: (gameId: string) => void;
  onCreateGame: (gameId: string) => void;
}

const GameLobby = ({ onJoinGame, onCreateGame }: GameLobbyProps) => {
  const [inviteCode, setInviteCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [waitingGames, setWaitingGames] = useState<any[]>([]);
  const { toast } = useToast();

  // Load waiting games
  useEffect(() => {
    loadWaitingGames();
  }, []);

  const loadWaitingGames = async () => {
    try {
      const { data, error } = await supabase
        .from('games')
        .select(`
          id,
          invite_code,
          created_at,
          profiles!games_player1_id_fkey(username)
        `)
        .eq('game_status', 'waiting')
        .order('created_at', { ascending: false })
        .limit(10);

      if (error) throw error;
      setWaitingGames(data || []);
    } catch (error) {
      console.error('Error loading games:', error);
    }
  };

  const createGame = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        toast({
          title: "Authentication required",
          description: "Please sign in to create a game",
          variant: "destructive"
        });
        return;
      }

      const { data, error } = await supabase
        .from('games')
        .insert({
          player1_id: user.id,
          game_status: 'waiting',
          invite_code: '' // Will be generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Game created!",
        description: `Share this code: ${data.invite_code}`,
      });

      onCreateGame(data.id);
    } catch (error) {
      console.error('Error creating game:', error);
      toast({
        title: "Error",
        description: "Failed to create game",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const joinGameByCode = async () => {
    if (!inviteCode.trim()) return;

    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        toast({
          title: "Authentication required",
          description: "Please sign in to join a game",
          variant: "destructive"
        });
        return;
      }

      const { data, error } = await supabase
        .from('games')
        .update({
          player2_id: user.id,
          game_status: 'active'
        })
        .eq('invite_code', inviteCode.toUpperCase())
        .eq('game_status', 'waiting')
        .select()
        .single();

      if (error || !data) {
        toast({
          title: "Error",
          description: "Game not found or already started",
          variant: "destructive"
        });
        return;
      }

      toast({
        title: "Joined game!",
        description: "Starting game...",
      });

      onJoinGame(data.id);
    } catch (error) {
      console.error('Error joining game:', error);
      toast({
        title: "Error",
        description: "Failed to join game",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const joinGame = async (gameId: string) => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        toast({
          title: "Authentication required",
          description: "Please sign in to join a game",
          variant: "destructive"
        });
        return;
      }

      const { data, error } = await supabase
        .from('games')
        .update({
          player2_id: user.id,
          game_status: 'active'
        })
        .eq('id', gameId)
        .eq('game_status', 'waiting')
        .select()
        .single();

      if (error || !data) {
        toast({
          title: "Error",
          description: "Failed to join game",
          variant: "destructive"
        });
        return;
      }

      onJoinGame(data.id);
    } catch (error) {
      console.error('Error joining game:', error);
      toast({
        title: "Error",
        description: "Failed to join game",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <div className="text-center">
        <h1 className="text-3xl font-bold bg-gradient-primary bg-clip-text text-transparent mb-2">
          LETTUS Multiplayer
        </h1>
        <p className="text-muted-foreground">Create or join a game to play with friends</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Create Game */}
        <Card className="p-6 bg-gradient-card">
          <h2 className="text-xl font-bold mb-4 text-center">Create Game</h2>
          <Button 
            onClick={createGame} 
            disabled={loading}
            className="w-full"
            size="lg"
          >
            {loading ? 'Creating...' : 'Create New Game'}
          </Button>
        </Card>

        {/* Join by Code */}
        <Card className="p-6 bg-gradient-card">
          <h2 className="text-xl font-bold mb-4 text-center">Join by Code</h2>
          <div className="space-y-3">
            <div>
              <Label htmlFor="inviteCode">Game Code</Label>
              <Input
                id="inviteCode"
                value={inviteCode}
                onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
                placeholder="Enter 6-digit code"
                maxLength={6}
                className="uppercase"
              />
            </div>
            <Button 
              onClick={joinGameByCode} 
              disabled={loading || !inviteCode.trim()}
              className="w-full"
              size="lg"
            >
              {loading ? 'Joining...' : 'Join Game'}
            </Button>
          </div>
        </Card>
      </div>

      {/* Available Games */}
      {waitingGames.length > 0 && (
        <Card className="p-6 bg-gradient-card">
          <h2 className="text-xl font-bold mb-4 text-center">Available Games</h2>
          <div className="space-y-2">
            {waitingGames.map((game) => (
              <div key={game.id} className="flex items-center justify-between p-3 bg-muted rounded-lg">
                <div>
                  <span className="font-medium">Game {game.invite_code}</span>
                  <span className="text-sm text-muted-foreground ml-2">
                    by {game.profiles?.username || 'Anonymous'}
                  </span>
                </div>
                <Button 
                  onClick={() => joinGame(game.id)}
                  disabled={loading}
                  size="sm"
                >
                  Join
                </Button>
              </div>
            ))}
          </div>
          <Button 
            onClick={loadWaitingGames}
            variant="outline"
            className="w-full mt-4"
          >
            Refresh
          </Button>
        </Card>
      )}
    </div>
  );
};

export default GameLobby;