// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muayyyoxhfdshoyvckny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11YXl5eW94aGZkc2hveXZja255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDI1MDEsImV4cCI6MjA3MDExODUwMX0.kWO5FS2Ia8WSN07usnm-Y0stair6tp52lGAzd3TUttQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});