// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://resjlesjbgdafytfxzzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlc2psZXNqYmdkYWZ5dGZ4enp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDM5NDYsImV4cCI6MjA3MDExOTk0Nn0.paowzIxAQgB50tf1HobGgspmfvXtGA5M8rENk80DRTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});